### ISSUE TITLE
"No file selected" on trying to filter very large file (>~60Mb)

### ISSUE THREAD

**Issue by gost-serb** [everettjf/vscode-filter-line#10]
When I'm trying to filter really large file Extention fails with message "No file selected".

Sample file for tests: [enwik8.txt.gz](https://github.com/everettjf/vscode-filter-line/files/2987960/enwik8.txt.gz)

**Comment by everettjf** [comment]
Got it, I'm on it.

**Comment by pdsharma0** [comment]
I am getting the same error on trying to filter a JSON file which is around 320 MB in size. Eagerly waiting for this fix! :)

**Comment by ghost** [comment]
遇到了同样的问题

**Comment by everettjf** [comment]
嗯。不好意思各位。最近太忙了～五一假期争取修复。
I will try to fix it in the 5.1 holiday

**Comment by jeffreylyg** [comment]
marked

**Comment by kniyer70** [comment]
I am getting the same error on trying to filter a 180 MB log file. Also I downloaded the most recent version 1.2.10 for Windows VS Code. Will be a great tool if it works.

**Comment by subprime** [comment]
Same behavior here.

**Comment by everettjf** [comment]
Sorry, everyone. I will try to fix the problem as soon as possible.

**Comment by gost-serb** [comment]
I think this issue related to VS Code in general, because `vscode.window.activeTextEditor` is `undefined` for big documents. Also, there is a ticket in vs-code repo about this problem: https://github.com/microsoft/vscode/issues/31078
So, I think the only one thing, that @everettjf could do now is modifying error message to something like "No file selected or opened file is too big".

**Comment by everettjf** [comment]
@GOST-UA Thanks for your detailed description. I will work on this issue this weekend. Really! 😢

**Comment by everettjf** [comment]
Yes, I confirmed that `vscode.window.activeTextEditor` is undefined when opening big documents. Trying to look for replacement instead of just prompt.

**Comment by everettjf** [comment]
Hi everyone, thank you for your proposals. 

I just published a new version which could deal with large files.

---

### Large file mode

Since [vscode's limitation](https://github.com/microsoft/vscode/issues/31078), when filter large files (e.g. >= 50MB), vscode extension cannot get the file name currently opened. But this extension provides an alternative. e.g. if you want to filter large file `~/log/file.log`, do follow steps below :

1. Create an empty file named `filterline` ( `~/log/filterline`) in the same directory with log file.
2. Try to filter the empty file `filterline`.
3. Now the extension will list all files in the same directory.
4. Choose the one (`~/log/file.log`) you want to filter.

**Comment by everettjf** [comment]
Thank you all. Sorry for my lazy :) @GOST-UA @subprime @kniyer70 @jeffreylyg @zpl-ai @pdsharma0

**Comment by gost-serb** [comment]
Geat! Did you think about add possibility to context menu for files in explorer sidebar?

**Comment by everettjf** [comment]
Emmm... context menu may be better.
I will create a new issue for this feature.

**Comment by chylex** [comment]
The original VS Code issue https://github.com/microsoft/vscode/issues/31078 is now a backlog candidate, it needs a few more upvotes to be accepted.

**Comment by gost-serb** [comment]
@chylex Great news! Upvoted, 2 left.

**Comment by Roemer** [comment]
Gave it the 20th vote ;)
